### ISSUE TITLE
Slack notifications with ApplicationSet controller

### ISSUE THREAD

**Issue by legigor** [argoproj-labs/argocd-notifications#270]
## Summary 

I've added the notification `notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-activity` to the template section of the `ApplicationSet` definition. On sync it started bombing my Slack with duplicated notifications. On the ArgoCD GUI I noticed the annotations for the selected Application been updated all the time with something like notification already sent, then this notification disappeared, then another Slack nmessage arrived, annotation updated and disappeared again and again.

The AppSet config looks like

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: the-cluster
spec:
  generators:
    - git:
        repoURL: git@github.com:company/the-cluster.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-activity      
    spec:
      project: default
      source:
        repoURL: git@github.com:company/the-cluster.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
```

## Diagnostics

What Kubernetes provider are you using? 
- Latest available on Azure AKS

What version of Argo CD and Argo CD Notifications are you running? 
- Argo CD 2.0
- Argo CD Notifications v1.0.2

```
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:28:58Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:28:58Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:00Z" level=info msg="Start processing" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/queuemeter
time="2021-04-28T16:29:00Z" level=info msg="Processing completed" app=argocd/queuemeter
time="2021-04-28T16:29:03Z" level=info msg="Start processing" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0 [app-sync-succeeded] true}]" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' already sent to '{slack platform-activity}'" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Processing completed" app=argocd/ops
time="2021-04-28T16:29:03Z" level=info msg="Start processing" app=argocd/ops
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexmt** [comment]
I think this is caused by https://github.com/argoproj-labs/applicationset/issues/180 . The fix is merged but not released yet.

**Comment by gdubya** [comment]
@alexmt Any rough estimate for when the next release will be out?

**Comment by ryota-sakamoto** [comment]
applicationset v0.2.0 was released.
https://github.com/argoproj-labs/applicationset/releases/tag/v0.2.0

**Comment by bitgandtter** [comment]
still not working for me after updating to all the latest versions. Anything I need to do aside?

**Comment by laloyalo** [comment]
Hello @bitgandtter , how are you configuring the annotation? I just did some testing with my own applications and found the following.
1. It looks like the solution worked on https://github.com/argoproj-labs/applicationset/pull/193 from the upstream project only works for annotations set in the `ApplicationSet` definition, not for [default/project subscriptions](https://argocd-notifications.readthedocs.io/en/stable/subscriptions/#default-subscriptions) like the ones set in `AppProjects` or defined in the `argocd-notifciations-cm`, this is because I first tried with the annotation in a project and it kept failing.
2. Once I set the annotation inside the `ApplicationSet` `spec.template.metadata.annotations` section, it worked just fine. Looking at the code and added test, it seems like the expected behavior. 
3. Additionally, I noticed that when adding the subscription annotation to the project, the key that the argocd-notification-controller adds (`notified.notifications.argoproj.io`), was removed after a couple seconds, which may indicate that the, which can be seen in the [code of the fix](https://github.com/argoproj-labs/applicationset/pull/193/files#diff-f721f839ed85ebb25331357d4d3008ec1fefd7dacf90c9d8720dae61f9ac90afR739).

Try configuring the annotation directly in your `ApplicationSet`s.

Greetings.

**Comment by bitgandtter** [comment]
thanks @laloyalo 

I have the following values for the notification chart

`
secret:
  items:
    slack-token: "${var.slackToken}"

triggers:
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
      oncePer: app.status.sync.revision
      send:
      - app-deployed

templates:
 template.app-deployed: |
   email:
     subject: New version of an application {{.app.metadata.name}} is up and running.
   message: |
     {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
   slack:
     attachments: |
       [{
         "title": "{{ .app.metadata.name}}",
         "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
         "color": "#18be52",
         "fields": [
         {
           "title": "Sync Status",
           "value": "{{.app.status.sync.status}}",
           "short": true
         },
         {
           "title": "Repository",
           "value": "{{.app.spec.source.repoURL}}",
           "short": true
         },
         {
           "title": "Revision",
           "value": "{{.app.status.sync.revision}}",
           "short": true
         }
         {{range $index, $c := .app.status.conditions}}
         {{if not $index}},{{end}}
         {{if $index}},{{end}}
         {
           "title": "{{$c.type}}",
           "value": "{{$c.message}}",
           "short": true
         }
         {{end}}
         ]
       }]
 template.app-health-degraded: |
   email:
     subject: Application {{.app.metadata.name}} has degraded.
   message: |
     {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} has degraded.
     Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
   slack:
     attachments: |-
       [{
         "title": "{{ .app.metadata.name}}",
         "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
         "color": "#f4c030",
         "fields": [
         {
           "title": "Sync Status",
           "value": "{{.app.status.sync.status}}",
           "short": true
         },
         {
           "title": "Repository",
           "value": "{{.app.spec.source.repoURL}}",
           "short": true
         }
         {{range $index, $c := .app.status.conditions}}
         {{if not $index}},{{end}}
         {{if $index}},{{end}}
         {
           "title": "{{$c.type}}",
           "value": "{{$c.message}}",
           "short": true
         }
         {{end}}
         ]
       }]
`

and I have the following ApplicationSet

`
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xyz
  namespace: argocd
spec:
  generators:
    - git:
...
  template:
    metadata:
      name: xyz
      namespace: argocd
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.slack: channel
        notifications.argoproj.io/subscribe.on-health-degraded.slack: channel
...
    spec:
...
`

and it keeps sending me notifications every 5 seconds even when the controller pod sais

`
time="2021-09-22T17:48:16Z" level=info msg="Notification about condition 'on-deployed.[0].y7b5sbwa2Q329JYH755peeq-fBs' already sent to '{slack monitor}'" app=argocd/xyz
`

what I'm missing?

**Comment by bitgandtter** [comment]
@laloyalo application set pod running image `quay.io/argoproj/argocd-applicationset:v0.2.0` I change to use the new `app.status.operationState.syncResult.revision` same result. I can share logs but what specifically are you looking for so I can search on the logs. the logs have some sensitive information that I cant share like repository and so on

**Comment by thuandt** [comment]
I'm using Telegram and have same issue, notifications were not sent with `defaultTriggers`
